name: valorant
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.3.2
  dio: ^5.1.0
  flutter_svg: ^2.0.4
  easy_localization: ^3.0.1
  sliver_tools: ^0.2.9
  video_player: ^2.6.0
  easy_image_viewer: ^1.2.0
  shared_preferences: ^2.0.20
  shimmer: ^2.0.0
  flex_color_scheme: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  custom_lint: ^0.3.2
  flutter_lints: ^2.0.1
  riverpod_lint: ^1.1.6

flutter:

  uses-material-design: true

  fonts:
   - family: SourceHanSansSC
     fonts:
       - asset: assets/fonts/SourceHanSansSC/SourceHanSansSC-ExtraLight.otf
         weight: 200
       - asset: assets/fonts/SourceHanSansSC/SourceHanSansSC-Light.otf
         weight: 300
       - asset: assets/fonts/SourceHanSansSC/SourceHanSansSC-Regular.otf
         weight: 400
       - asset: assets/fonts/SourceHanSansSC/SourceHanSansSC-Medium.otf
         weight: 500
       - asset: assets/fonts/SourceHanSansSC/SourceHanSansSC-Bold.otf
         weight: 700
       - asset: assets/fonts/SourceHanSansSC/SourceHanSansSC-Heavy.otf
         weight: 900

  assets:
    - assets/svg/Weapons.svg
    - assets/translations/

