name: valorant
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.3.2
  dio: ^5.0.3
  flutter_svg: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  custom_lint: ^0.3.2
  flutter_lints: ^2.0.0
  riverpod_lint: ^1.1.6

flutter:

  uses-material-design: true

  fonts:
   - family: Noto_Serif_SC
     fonts:
       - asset: assets/fonts/Noto_Serif_SC/NotoSerifSC-ExtraLight.otf
         weight: 200
       - asset: assets/fonts/Noto_Serif_SC/NotoSerifSC-Light.otf
         weight: 300
       - asset: assets/fonts/Noto_Serif_SC/NotoSerifSC-Regular.otf
         weight: 400
       - asset: assets/fonts/Noto_Serif_SC/NotoSerifSC-Medium.otf
         weight: 500
       - asset: assets/fonts/Noto_Serif_SC/NotoSerifSC-SemiBold.otf
         weight: 600
       - asset: assets/fonts/Noto_Serif_SC/NotoSerifSC-Bold.otf
         weight: 700
       - asset: assets/fonts/Noto_Serif_SC/NotoSerifSC-Black.otf
         weight: 900

  assets:
    - assets/svg/Weapons.svg

